name: '|| Project Awake ||'
favicon: null
layout_spectrum: 0.88704
typography_spectrum: 0.9068
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2c2c2c'
    - '#120d09'
    - '#b7b1a3'
    - '#696a64'
    - '#dacfbd'
  brandStrength: 0.6875
  lightness: 0.5
  saturation: 0.8125
  rhythmicContrast: 1
purpose: []
