analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.6875
  brandStrength: 1
  lightness: 0.6875
  brandColors:
    - '#040000'
    - '#CAB4A7'
    - '#EDEDEF'
    - '#495561'
    - '#8A6A5D'
  rhythmicContrast: 0.5
typography_spectrum: 0.8555317
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 1
favicon: null
name: '|| Project Awake ||'
