analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
layout_spectrum: 0.7277121
color:
  saturation: 0.792159
  brandStrength: 0.6875
  rhythmicContrast: 0.8233083
  brandColors:
    - '#2d2b31'
    - '#6f716b'
    - '#aba99c'
    - '#dcd0c1'
    - '#faf0e6'
  lightness: 0.2250268
purpose: []
cta:
  bucket: null
  version: null
  domain: null
favicon: null
name: '|| Project Awake ||'
typography_spectrum: 0.8899033
