name: '|| Project Awake ||'
favicon: null
layout_spectrum: 0.88704
typography_spectrum: 0.9068
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f9f2df'
    - '#b3a588'
    - '#7a745e'
    - '#a84f3d'
    - '#0b0d0f'
  brandStrength: 0.8125
  lightness: 0.125
  saturation: 0.125
  rhythmicContrast: 1
purpose: []
